dataset:
    pos_img_dir: ./INRIAPerson/Train/pos/
    neg_img_dir: ./INRIAPerson/Train/neg/
    annotation_dir: ./INRIAPerson/Train/annotations/
output:
    cropped_dir: ./output/cropped/
    bounding_box_out_dir: ./output/bounding_box/
    out_dir: ./output/out/
    cascade_xml: ./output/hog2/